apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://10.10.10.80:8901/k8s/clusters/local"

users:
- name: "local"
  user:
    token: "kubeconfig-user-dszl7w42bj:b24hwpx4v2vn4682tvhbhdvgjb67hqllf96ncwl5wqb7dhn8h98ncg"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
