---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /docker/sonarr/config:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - ChiralNet

networks:
  ChiralNet:
    external: true