---
version: "3.7"
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /home/docker/fail2ban/data:/data
      - /var/log/auth.log:/var/log/auth.log:ro
      - /home/docker/nginx-proxy-manager/data/logs/:/log/npm/:ro
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=365d
      - SSMTP_HOST=smtp.gmail.com
      - SSMTP_PORT=587
      - SSMTP_HOSTNAME=npm.lan
      - SSMTP_USER=claubervs@gmail.com
      - SSMTP_PASSWORD=
      - SSMTP_TLS=YES

volumes:
  nginx-proxy-manager-data:
    external: true
...