---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - ChiralNet
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  ChiralNet:
    external: true