---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - sabnzbd-data:/config
      - /mnt/media/usenet:/downloads #optional
      # - /path/to/incomplete/downloads:/incomplete-downloads #optional
    ports:
      - 8082:8080
    restart: unless-stopped
    networks:
      - ChiralNet

volumes:
  sabnzbd-data:
    external: true

networks:
  ChiralNet:
    external: true
...