---
version: '3.3'
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - HOST_WHITELIST_ENTRIES='docker.lan.claubersantos.com,sabnzbd.lan.claubersantos.com,sabnzbd.claubersantos.com,sabnzbd'
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /docker/sabnzbd/config:/config
      - /mnt/media:/media
      # - /mnt/media/usenet:/downloads #optional
      # - /mnt/media/watched/usenet:/watched
      # - /path/to/incomplete/downloads:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - ChiralNet

networks:
  ChiralNet:
    external: true