---

version: '3.3'
services:
  guacamole:
    container_name: guacamole
    hostname: guacamole
    image: jwetzell/guacamole
    ports:
      - 7777:8080
    volumes:
      - postgres:/config
    networks:
      - ChiralNet
    # environment:
      # - 'EXTENSIONS=auth-ldap,auth-openid,'
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  ChiralNet:
    external: true

...