---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /docker/radarr/config:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - ChiralNet

networks:
  ChiralNet:
    external: true