---
version: "2.1"
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=passwd
    networks:
      - ChiralNet


  # mariadb:
  #   image: lscr.io/linuxserver/mariadb:latest
  #   container_name: mariadb
  #   hostname: mariadb
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - MYSQL_ROOT_PASSWORD=passwd
  #     - TZ=America/Toronto
  #   volumes:
  #     - /mnt/persist/config/mariadb:/config
  #   ports:
  #     - 3306:3306
  #   restart: unless-stopped
  #   networks:
  #     - ChiralNet
  
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    ports:
      - 3333:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    networks:
      - ChiralNet
  
  # mysql-workbench:
  #   image: lscr.io/linuxserver/mysql-workbench:latest
  #   container_name: mysql-workbench
  #   hostname: mysql-workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Toronto
  #   volumes:
  #     - /mnt/persist/config/mysql-workbench:/config
  #   ports:
  #     - 3000:3000
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped
  #   networks:
  #     - ChiralNet
  #   depends_on:
  #     - mariadb

networks:
  ChiralNet:
    external: true
...
