---
version: '3.3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    ports:
      - 8081:80
    volumes:
      - /home/clauber/docker/config/vaultwarden/data:/data
    networks:
      - ChiralNet
    restart: unless-stopped

networks:
  ChiralNet:
    external: true
...