---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=changeMe
      - TZ=America/Toronto
    volumes:
      - /mnt/persist/config/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - ChiralNet

networks:
  ChiralNet:
    external: true
...
