---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - JELLYFIN_PublishedServerUrl=10.10.10.90 #optional
    volumes:
      # - jellyfin-data:/config
      - /docker/jellyfin/config:/config
      - /mnt/media/content/series:/data/series
      - /mnt/media/content/movies:/data/movies
      - /mnt/media/content/anime:/data/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    networks:
      - ChiralNet

volumes:
  jellyfin-data:
    external: true

networks:
  ChiralNet:
    external: true