---
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: uptime-kuma
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    networks:
      - ChiralNet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  data:
    driver: local

networks:
  ChiralNet:
    external: true
...
